server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - After=2024-03-15T23:26:32.559676600+08:00[Asia/Hong_Kong] # 指定时间之后x可访问
#            - Cookie=name,tjl #cookie中需携带key为name 值为tjl的请求可访问
#            - Header=token, \d+ #header中需携带key为token 值为正整数的请求可访问
#            - Host=**.tjl.com,127.0.0.1**
#            - Query=userId, \d+ #query中需携带key为userId 值为正整数的请求可访问
#            - My=S
        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service               #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由
        - id: pay_route3
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/filter/**
          filters:
            - My=token
#            - RedirectTo=302,https://www.baidu.com
#            - SetPath=/pay/gateway/{url}
#            - AddRequestHeader=tjl,123456
#            - SetRequestHeader=tjl,hello
#            - AddRequestParameter=userId,123456
#            - RemoveRequestParameter=userId